### PR TITLE
Refactors for nicer code - merged

### PR DESCRIPTION
**Pull request by flaszlo2000**
First of all, I do not own a SD yet so plese forgive me if I made a mistake by removing a sleep call or something.
(I found your post on Reddit)

I tried to level up your code a bit by removing some antipatters (like the lambda usage in your way, path/beta constant with better variable names, not using a main function, etc) and make the code more readable.

### CODE REVIEW

**Comment by realmthyx** [comment]
Hello! Actually someone found my software LMFAO. Thanks for refactoring the code, I just made it in like a hour and didnt have any knowledge with advanced Python whatsoever, thanks for reaching, we will put this in the next update!

**Comment by realmthyx** [comment]
The sleep calls were for aesthetic purposes only to make the user read stuff from the console.
This is not for Steam Deck itself, rather for Windows and Linux versions of Steam to get the Steam Deck **UI**.
Thank you so much for helping me!

**Comment by flaszlo2000** [comment]
> Thank you so much for helping me!

You're welcome :)

I used one more trcik just to reduce indentation a bit, you can see it in the last commit

**Comment by flaszlo2000** [comment]
If you accept these changes, will you close this PR after merge?

**Comment by realmthyx** [comment]
I accept these changes, once again thank you so much!

**Pull request merged**
